### ISSUE TITLE
Code formatting and .editorconfig

### ISSUE THREAD

**Issue by grantpalin** [Beanstream/beanstream-php#8]
A recent pull request and a comment about spaces versus tabs had me thinking about establishing a standard editor configuration for this project.

http://editorconfig.org/ outlines the file format for defining such a standard. I was thinking of at the very least using spaces, four to a tab, for indenting purposes. Another idea was to enforce the trimming of trailing whitespace.

I'm conflicted on the former idea since the project seems to use spaces and tabs almost evenly. A subsequent update could be done to convert to all of one or the other for consistency.

Any opinions on this?

**Comment by sploreg** [comment]
I wouldn't enforce strict rules as it can turn people off from submitting pull requests. However we can still accept some standard formatting and adjust pull request whitespace after it has been merged. Using 4 spaces instead of a tab is fine with me.

**Comment by grantpalin** [comment]
With the provided file, editors which support editorconfig should automatically insert spaces instead of tabs, strip trailing whitespace, and ensure that each file ends with a newline.
